# Generated by Django 2.2.4 on 2019-08-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=30)),
                ('url_object_id', models.CharField(max_length=50)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('top', models.IntegerField(max_length=5)),
                ('url', models.CharField(max_length=300)),
                ('url_object_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('play_able', models.CharField(default='', max_length=10)),
                ('star', models.CharField(default='', max_length=10)),
                ('year', models.CharField(default='', max_length=60)),
                ('comments_num', models.CharField(default='', max_length=20)),
                ('country', models.CharField(default='', max_length=20)),
                ('actor', models.CharField(default='', max_length=100)),
                ('movie_type', models.CharField(default='', max_length=40)),
                ('director', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=255)),
                ('image_path', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User_favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=30)),
                ('url_object_id', models.CharField(max_length=50)),
                ('watched', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_list',
            fields=[
                ('user_id', models.AutoField(max_length=30, primary_key=True, serialize=False, verbose_name='user_id')),
                ('username', models.CharField(max_length=30)),
                ('userpassword', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
    ]
