# Generated by Django 2.2.4 on 2019-08-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190824_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='user_id',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='user_id'),
        ),
    ]
