# Generated by Django 2.2.4 on 2019-08-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190825_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='usertype',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
