# Generated by Django 2.2.4 on 2019-08-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190825_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user_favorite',
            name='user_id',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='userpassword',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user_list',
            name='usertype',
            field=models.CharField(default='user', max_length=8),
        ),
    ]
