# Generated by Django 2.2.4 on 2019-08-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190825_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_list',
            name='usertype',
            field=models.CharField(blank=True, default='user', max_length=8, null=True),
        ),
    ]
