# Generated by Django 2.2.4 on 2019-08-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190825_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
