# Generated by Django 2.2.4 on 2019-08-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20190825_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='top',
            field=models.IntegerField(),
        ),
    ]
