# Generated by Django 2.2.4 on 2019-08-25 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20190825_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_list',
            old_name='username',
            new_name='user_name',
        ),
    ]
