# Generated by Django 2.2.4 on 2019-08-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20190826_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_favorite',
            name='url_object_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieInfo'),
        ),
    ]
