# Generated by Django 2.2.4 on 2019-08-25 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20190826_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_favorite',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.User_list'),
        ),
    ]
