# Generated by Django 2.2.4 on 2019-08-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20190826_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_favorite',
            name='url_object_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user_favorite',
            name='user_id',
            field=models.CharField(max_length=11),
        ),
    ]
